version: '3'
services:
  app:
    container_name: equity_wallet_api
    restart: always
    build: .
    depends_on:
      - database
    ports:
      - ${DOCKER_PORT}:${API_PORT}
    volumes:
      - .:/usr/equity-wlallet/app
      - /usr/equity-wlallet/app/node_modules
    environment:
      DB_HOST: database
      DB_PORT: 5432
  database:
    container_name: equity_wallet_db
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - ${DB_PORT}:5432
