name: "CI (Integracao Continua): Primeira Action"
on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  example:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.17.1
      
      - name: Install depedencia
        run: sudo yarn

      - name: Build-DB and Create a new database
        run: docker compose  -f "docker-compose.yml" up -d --build database 
        

      - name: Test
        run: yarn test
      

